### ISSUE TITLE
W/System.err: java.io.IOException: Bluetooth not initialized

### ISSUE THREAD

**Issue by amigax** [chen-fishbein/bluetoothle-codenameone#10]
Getting this error with the bluetooth lib on Android (samsung s7 -  Android 8.0)

W/System.err: java.io.IOException: Bluetooth not initialized
W/System.err:     at com.codename1.cordova.Cordova.execute(Cordova.java:33)
W/System.err:     at com.codename1.bluetoothle.Bluetooth.enable(Bluetooth.java:85)
W/System.err:     at userclasses.MainForm.startBluetooth(MainForm.java:55)
W/System.err:     at com.pippa.hobmonitor.MyApplication.start(MyApplication.java:41)
W/System.err:     at com.pippa.hobmonitor.MyApplicationStub.run(MyApplicationStub.java:163)
W/System.err:     at com.pippa.hobmonitor.MyApplicationStub$1.run(MyApplicationStub.java:107)
W/System.err:     at com.codename1.ui.Display.processSerialCalls(Display.java:1298)
W/System.err:     at com.codename1.ui.Display.mainEDTLoop(Display.java:1093)
W/System.err:     at com.codename1.ui.RunnableWrapper.run(RunnableWrapper.java:120)
W/System.err:     at com.codename1.impl.CodenameOneThread$1.run(CodenameOneThread.java:60)
W/System.err:     at java.lang.Thread.run(Thread.java:764)

**Comment by amigax** [comment]
seems to be related to the json lib not working 

 Exception: java.lang.NoSuchMethodError - No direct method <init>(Ljava/util/Map;)V in class Lca/weblite/codename1/json/JSONObject; or its super classes (declaration of 'ca.weblite.codename1.json.JSONObject' appears in /data/app/com.pippa.hobmonitor-i555BGum4BjW27o1gIXtCQ==/base.apk)
W/System.err: java.lang.NoSuchMethodError: No direct method <init>(Ljava/util/Map;)V in class Lca/weblite/codename1/json/JSONObject; or its super classes (declaration of 'ca.weblite.codename1.json.JSONObject' appears in /data/app/com.pippa.hobmonitor-i555BGum4BjW27o1gIXtCQ==/base.apk)
